//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class contex2021Container : DbContext
    {
        public contex2021Container()
            : base("name=contex2021Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vorod> vorods { get; set; }
        public virtual DbSet<khoroje> khorojes { get; set; }
        public virtual DbSet<khalaye_mayoub> khalaye_mayoub { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<personel> personels { get; set; }
    }
}
